Repository Dartt0n/birthy, pull requests merged in 2022-07, with the labels that each got.

#11 Feature/add count to nearest
  birthy/handlers/commands.py
  birthy/utils/parser.py
  birthy/utils/scripts.py
Labels: feature request

#13 Fixed docker compose database volumes
  docker-compose.yml
Labels: bug

#15 Added the `/all` command
  birthy/handlers/commands.py
  birthy/utils/scripts.py
Labels: feature request

#16 Feature/month command
  birthy/handlers/commands.py
  birthy/utils/scripts.py
Labels: feature request

#19 Added getting birthday by replying to message and parsing nickname with @
  birthy/handlers/commands.py
  birthy/utils/parser.py
Labels: enhancement
